// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwwwxrfxxgpcmegljjcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3d3d4cmZ4eGdwY21lZ2xqamN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzOTA3ODUsImV4cCI6MjA4NDk2Njc4NX0.i0CHpQAKfDTqKX_YTtuidkY2hq1rThE2XxqhJGs0IW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
